version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: air-resume-db
    environment:
      - POSTGRES_DB=air_resume_mate_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  pg-data: